[package]
name = "cuicui_richtext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
bevy = { version = "0.10", default-features = false, features = ["bevy_render", "bevy_core_pipeline", "bevy_text", "bevy_ui"] }
winnow = "0.4.4"

[dev-dependencies]
pretty_assertions_sorted = "1.2.1"
bevy = { version = "0.10", features = ["png", "x11", "bevy_asset", "bevy_render" ] }
